services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: aspen_dev
      POSTGRES_USER: aspen_user
      POSTGRES_PASSWORD: aspen_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aspen_user -d aspen_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://aspen_user:aspen_pass@db:5432/aspen_dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: 