"""add_branch_label_to_node_nodes

Revision ID: 836a4ab0e5a9
Revises: 2bb7a25865d5
Create Date: 2025-09-03 02:24:41.715879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '836a4ab0e5a9'
down_revision: Union[str, Sequence[str], None] = '2bb7a25865d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_nodes', sa.Column('branch_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_services_api_key_hash'), table_name='services')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_services_api_key_hash'), 'services', ['api_key_hash'], unique=False)
    op.drop_column('node_nodes', 'branch_label')
    # ### end Alembic commands ###
